# 1. Notifications
notifications:
  slack:
    rooms:
      - secure: "XcSUTvsCwQ/CZUaxZCmmR1a/69Nb810pZBK6PHw4BwBolPG5BUq6Gvja874oJDvGTYHGHz06OvFGVmiX9dO42u4x2NrbXXwjWebKTPtmR4ArYdgJh2Mc0Lhvx8VLwNcsu19dYAo/+AoxKhX9yUppJAcmoVDdT/GwvG4+lEE4i29hDAR8bHhSOWlCpH2+pHQRhtTllUsVB7dsv822HtQiWT8dLsUiRgi8TsIF5qXOgbTmZG4VbnlEjAZwRxdVbqLRTTGliWPKEe5hv+bxYUkIH200CVKL/GHV1dIOyfqWzn+xEZVmPSxfDvTZ3yz00woZO3PY5DpfHbAjxsRjheYDc2ZkWZ/3Q1X8Mk6abz+ktKvNx97wVKWnuGT9geM4g88U28R5IJjzJ7UcqnjSZ2xu/DHfaOnXmSyGb6IyLFEldDaM7SVv0e2N/AImhVDs8a6VhYh5H5vqnkw7sWAmYO49bSZxwPnBtzOUkycKjgRHZ/kqFCx08BtF5kPQQgpt+g0HzQUzdVNNTNtP5MoXbKdTcZ5JEQZziVlCVQpsHYnyoAKWqSKrt4LNK8gRkcd7bbQvUyFBtrScFhMB6L5BGBnDe/K8Oy2VGHSwdnW+DyvXGrXOLf0Si5m5QN8DHqSRcrEmhRnWOJSm0AhXdi424FaHNHBCTLadYJ7CC3eEypCfd+A=" # atex-ci
      - secure: "TXVx622hYnMEZBU4RmGIdY4+Am54fdhaZWx1lFePfWb+vBEPrb0hiCms8TetSsL3IOAKeS0iHVvfZGwvAWfyY+20T3hoUmbuZC961/0b8hDH1v+mHW5uusfs45VnJsh29wjsjArCJz3xyz2C64ecFDWAYg4xsArTtDPvMqnaJVzeWF5sJgNaWVlhJPN8crIXF4R6bLQDMxOZJySzUwF+Jz9KgGLzUy14v3THlMH+s2CnPKO3GLhw1lRzcXFGi6A3IgfBt/MZywMkNJ0vetgjNgzFdMzE5GMqg6l/hRrcfHh6/maCDgQqIJ/bT1lAAlGOs9ytONr0p0nV1t6SZFZwza6aegolQt8BvIKWDoHJ1wnyOgMNRoOvqUKZvmig3fWs3yegbMbdVefAj9/yGsmtvByp6LCPjj1WEI7PtwwcECD/Tti/1Qhz7CtDQ3Tzu7WKdoA7gZc3luljd5+/VZ1gfUOfzidexEo+nn6Nv82aAIwpHGnAFcJnsc9wBBUHDwJ+o7afeessw8NQtqugipYkBh0udmwPohAdNYQHXVPVOnLNBIhMe+QOuviOle3Ba78UbKj1ZeBIW5bMtfiRLO0aGOCRGFtlUY5QuzBBp0yNScpABX73vVsmGsvHNWIPYDZsgBmDuvWlOz3yElO8FVvK4qLsAQGRepN8iL+WAlcJBxU=" # cloud-ci
    on_success: :change
    on_pull_requests: false

# 2. Env
# env:

# 3. Git
# git:
branches:
  except:
    - /^f\// # feature branches require PR

# 4. Bootstrap
os: linux
dist: trusty
sudo: false
language:
  - node_js
node_js:
  - node
# addons:
before_cache: ./.travis.sh before_cache
cache:
  directories:
    - $HOME/.local
    - $HOME/.npm
    - $HOME/.pip-cache/
    - $HOME/Library/Caches/Homebrew
    - /tmp/support-firecloud.cache
    - node_modules

# 5. Steps
before_install: ./.travis.sh before_install
install: ./.travis.sh install
before_script: ./.travis.sh before_script
script: ./.travis.sh script
after_success: ./.travis.sh after_success
after_failure: ./.travis.sh after_failure
after_script: ./.travis.sh after_script

# 6. Deploy
before_deploy: ./.travis.sh before_deploy
# deploy:
after_deploy: ./.travis.sh after_deploy
